[package]
name = "fiveos_riscv"
version = "0.2.0"
authors = ["Daniel Boyle <boylede+github@gmail.com>"]
edition = "2021"

[dependencies]
volatile = "0.4.5"
num_enum = {version="0.7.0", default-features = false}
paste = "1.0"
